services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - kafka-network

  api-gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC: "object.events"
    depends_on:
      - kafka
    networks:
      - kafka-network

  distribute-service:
    build:
      context: .
      dockerfile: ./services/distribute-service/Dockerfile
    environment:
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC: "object.events"
      KAFKA_GROUP_ID: "file-consumer-group"
      STORAGE_PATH: "/data/storage"
      MINIO_BUCKET: "files"
    volumes:
      - file-storage:/data/storage
    depends_on:
      - kafka
      - minio
    networks:
      - kafka-network

  storage-service:
    build:
      context: .
      dockerfile: ./services/storage-service/Dockerfile
    environment:
      STORAGE_PATH: "/data/storage"
      MINIO_BUCKET: "files"
    volumes:
      - file-storage:/data/storage
    depends_on:
      - kafka
      - minio
    networks:
      - kafka-network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Web Console
    volumes:
      - minio-data:/data
    networks:
      - kafka-network

volumes:
  file-storage:
  minio-data:

networks:
  kafka-network:
    driver: bridge
