// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: metadata.proto

package metadata_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveFileMetadataRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,2,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	StoredFilename   string                 `protobuf:"bytes,3,opt,name=stored_filename,json=storedFilename,proto3" json:"stored_filename,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SaveFileMetadataRequest) Reset() {
	*x = SaveFileMetadataRequest{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileMetadataRequest) ProtoMessage() {}

func (x *SaveFileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileMetadataRequest.ProtoReflect.Descriptor instead.
func (*SaveFileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *SaveFileMetadataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveFileMetadataRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *SaveFileMetadataRequest) GetStoredFilename() string {
	if x != nil {
		return x.StoredFilename
	}
	return ""
}

type SaveFileMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFileMetadataResponse) Reset() {
	*x = SaveFileMetadataResponse{}
	mi := &file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFileMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileMetadataResponse) ProtoMessage() {}

func (x *SaveFileMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileMetadataResponse.ProtoReflect.Descriptor instead.
func (*SaveFileMetadataResponse) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *SaveFileMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveFileMetadataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFileMetadataRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,2,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetFileMetadataRequest) Reset() {
	*x = GetFileMetadataRequest{}
	mi := &file_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataRequest) ProtoMessage() {}

func (x *GetFileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetFileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileMetadataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFileMetadataRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

type GetFileMetadataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StoredFilename string                 `protobuf:"bytes,1,opt,name=stored_filename,json=storedFilename,proto3" json:"stored_filename,omitempty"`
	Found          bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFileMetadataResponse) Reset() {
	*x = GetFileMetadataResponse{}
	mi := &file_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataResponse) ProtoMessage() {}

func (x *GetFileMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetFileMetadataResponse) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileMetadataResponse) GetStoredFilename() string {
	if x != nil {
		return x.StoredFilename
	}
	return ""
}

func (x *GetFileMetadataResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListUserFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserFilesRequest) Reset() {
	*x = ListUserFilesRequest{}
	mi := &file_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserFilesRequest) ProtoMessage() {}

func (x *ListUserFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserFilesRequest.ProtoReflect.Descriptor instead.
func (*ListUserFilesRequest) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserFilesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUserFilesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalFilenames []string               `protobuf:"bytes,1,rep,name=original_filenames,json=originalFilenames,proto3" json:"original_filenames,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListUserFilesResponse) Reset() {
	*x = ListUserFilesResponse{}
	mi := &file_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserFilesResponse) ProtoMessage() {}

func (x *ListUserFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserFilesResponse.ProtoReflect.Descriptor instead.
func (*ListUserFilesResponse) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserFilesResponse) GetOriginalFilenames() []string {
	if x != nil {
		return x.OriginalFilenames
	}
	return nil
}

type DeleteFileMetadataRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,2,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteFileMetadataRequest) Reset() {
	*x = DeleteFileMetadataRequest{}
	mi := &file_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileMetadataRequest) ProtoMessage() {}

func (x *DeleteFileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileMetadataRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFileMetadataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteFileMetadataRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

type DeleteFileMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileMetadataResponse) Reset() {
	*x = DeleteFileMetadataResponse{}
	mi := &file_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileMetadataResponse) ProtoMessage() {}

func (x *DeleteFileMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileMetadataResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileMetadataResponse) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFileMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteFileMetadataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\x12\x10metadata_service\"\x88\x01\n" +
	"\x17SaveFileMetadataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11original_filename\x18\x02 \x01(\tR\x10originalFilename\x12'\n" +
	"\x0fstored_filename\x18\x03 \x01(\tR\x0estoredFilename\"N\n" +
	"\x18SaveFileMetadataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"^\n" +
	"\x16GetFileMetadataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11original_filename\x18\x02 \x01(\tR\x10originalFilename\"X\n" +
	"\x17GetFileMetadataResponse\x12'\n" +
	"\x0fstored_filename\x18\x01 \x01(\tR\x0estoredFilename\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"/\n" +
	"\x14ListUserFilesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x15ListUserFilesResponse\x12-\n" +
	"\x12original_filenames\x18\x01 \x03(\tR\x11originalFilenames\"a\n" +
	"\x19DeleteFileMetadataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11original_filename\x18\x02 \x01(\tR\x10originalFilename\"P\n" +
	"\x1aDeleteFileMetadataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb7\x03\n" +
	"\x0fMetadataService\x12i\n" +
	"\x10SaveFileMetadata\x12).metadata_service.SaveFileMetadataRequest\x1a*.metadata_service.SaveFileMetadataResponse\x12f\n" +
	"\x0fGetFileMetadata\x12(.metadata_service.GetFileMetadataRequest\x1a).metadata_service.GetFileMetadataResponse\x12`\n" +
	"\rListUserFiles\x12&.metadata_service.ListUserFilesRequest\x1a'.metadata_service.ListUserFilesResponse\x12o\n" +
	"\x12DeleteFileMetadata\x12+.metadata_service.DeleteFileMetadataRequest\x1a,.metadata_service.DeleteFileMetadataResponseBcZagithub.com/ArtemChepenkov/golang-crud-s3-storage/services/metadata-service/proto;metadata_serviceb\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_metadata_proto_goTypes = []any{
	(*SaveFileMetadataRequest)(nil),    // 0: metadata_service.SaveFileMetadataRequest
	(*SaveFileMetadataResponse)(nil),   // 1: metadata_service.SaveFileMetadataResponse
	(*GetFileMetadataRequest)(nil),     // 2: metadata_service.GetFileMetadataRequest
	(*GetFileMetadataResponse)(nil),    // 3: metadata_service.GetFileMetadataResponse
	(*ListUserFilesRequest)(nil),       // 4: metadata_service.ListUserFilesRequest
	(*ListUserFilesResponse)(nil),      // 5: metadata_service.ListUserFilesResponse
	(*DeleteFileMetadataRequest)(nil),  // 6: metadata_service.DeleteFileMetadataRequest
	(*DeleteFileMetadataResponse)(nil), // 7: metadata_service.DeleteFileMetadataResponse
}
var file_metadata_proto_depIdxs = []int32{
	0, // 0: metadata_service.MetadataService.SaveFileMetadata:input_type -> metadata_service.SaveFileMetadataRequest
	2, // 1: metadata_service.MetadataService.GetFileMetadata:input_type -> metadata_service.GetFileMetadataRequest
	4, // 2: metadata_service.MetadataService.ListUserFiles:input_type -> metadata_service.ListUserFilesRequest
	6, // 3: metadata_service.MetadataService.DeleteFileMetadata:input_type -> metadata_service.DeleteFileMetadataRequest
	1, // 4: metadata_service.MetadataService.SaveFileMetadata:output_type -> metadata_service.SaveFileMetadataResponse
	3, // 5: metadata_service.MetadataService.GetFileMetadata:output_type -> metadata_service.GetFileMetadataResponse
	5, // 6: metadata_service.MetadataService.ListUserFiles:output_type -> metadata_service.ListUserFilesResponse
	7, // 7: metadata_service.MetadataService.DeleteFileMetadata:output_type -> metadata_service.DeleteFileMetadataResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
